default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

tenants: &tenants
  <% tenants = YAML.load_file(Rails.root.join("config", "tenant.yml"), aliases: true)[Rails.env].keys %>
  <% tenants.each do |tenant| %>
  <%= tenant %>:
    <<: *default
    database: storage/<%= "#{Rails.env}_#{tenant}" %>.sqlite3
    migrations_paths: db/migrate
  <% end %>

development:
  <<: *tenants

test:
  <<: *tenants

production:
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  <<: *tenants
