default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: csa_admin_development
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: csa_admin_test
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
