:queues:
  - [critical, 5]
  - [default, 2]
  - low
:schedule:
  billing_snapshot:
    cron: '0 45-59/1 23 28-31 * *'
    queue: low
    class: Scheduled::BillingSnapshotBatchJob
    description: "Create or update quarter billing snapshot during the last 15 minutes of each quarter"
  daily:
    cron: '5 0 0 * * *'
    queue: low
    class: Scheduled::DailyBatchJob
    description: "Daily checks and updates"
  newsletter_sync_list:
    cron: '0 0 1 * * *'
    queue: low
    class: Scheduled::NewsletterSyncListBatchJob
    description: "Sync members with Mailchimp audience list"
  postmark_sync_suppressions:
    every: '1h'
    queue: low
    class: Scheduled::PostmarkSyncSuppressionsBatchJob
    description: "Sync Postmark suppressions"
