:queues:
  - [critical, 5]
  - [default, 2]
  - low
:scheduler:
  :schedule:
    billing_invoices:
      cron: '0 0 5 * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::BillingMembersInvoicerJob
      description: "Automatically create and send new invoices"
    billing_shop_orders:
      cron: '0 45 4 * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::BillingShopOrdersAutoInvoicerJob
      description: "Automatically invoice shop orders"
    billing_payments:
      cron: '0 0 4 * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::BillingPaymentsProcessorJob
      description: "Process all new payments from the bank"
    billing_snapshot:
      cron: '0 45-59/1 23 28-31 * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::BillingSnapshotJob
      description: "Create or update quarter billing snapshot during the last 15 minutes of each quarter"
    chores:
      cron: '5 0 0 * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::ChoresJob
      description: "Daily chores (checks and updates)"
    notifier_daily:
      cron: '0 30 4 * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::NotifierDailyJob
      description: "Daily notifications handler"
    notifier_hourly:
      cron: '0 0 * * * *'
      queue: low
      class: ScheduledJob
      args: Scheduled::NotifierHourlyJob
      description: "Hourly notifications handler"
    postmark_sync_suppressions:
      every: '1h'
      queue: low
      class: ScheduledJob
      args: Scheduled::PostmarkSyncSuppressionsJob
      description: "Sync Postmark suppressions"
