name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libvips and pdftoppm
        run: |
          sudo apt-get update -qq -o Acquire::Retries=3
          sudo apt-get install -y --fix-missing -qq -o Acquire::Retries=3 libvips poppler-utils

      - name: Install Ruby and run Bundler install with cache
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.js and run npm install
        uses: actions/setup-node@v4
      - run: npm install

      - name: Run lint:check
        run: bin/rails lint:check
