name: Rubocop and ERB Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby and run Bundler install with cache
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run lint:check
      run: bin/rails lint:check
