name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y libvips

    - name: Install Ruby and run Bundler install with cache
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Zurich

    - name: Rails tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        bin/rails db:setup
        bin/rails test:prepare
        bin/rspec
